import type { Metadata } from "next";
import { Geist, Geist_Mono, Roboto  } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});
const roboto = Roboto({
  subsets: ["latin"], // subset latin cukup untuk bahasa Indonesia & Inggris
  weight: ["400", "500", "700"], // pilih bobot yang mau dipakai
  variable: "--font-roboto", // optional: biar bisa dipakai di Tailwind
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={`${roboto.variable}`}>
      <body
        className={`${roboto.className}`}
      >
        {children}
      </body>
    </html>
  );
}
